CREATE TABLE `matches` (
	`id` text PRIMARY KEY NOT NULL,
	`player_a_id` text NOT NULL,
	`player_b_id` text NOT NULL,
	`tournament` text,
	`round` text,
	`surface` text,
	`start_time_utc` text NOT NULL,
	`best_of` integer DEFAULT 3 NOT NULL,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`player_a_id`) REFERENCES `players`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`player_b_id`) REFERENCES `players`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `players` (
	`id` text PRIMARY KEY NOT NULL,
	`canonical_name` text NOT NULL,
	`display_name` text NOT NULL,
	`first_name` text,
	`last_name` text,
	`slug` text NOT NULL,
	`rank` integer,
	`peak_rank` integer,
	`elo` integer,
	`hard_elo` integer,
	`clay_elo` integer,
	`grass_elo` integer,
	`plays` text,
	`hand` text,
	`photo_url` text,
	`birth_year` integer,
	`height_cm` integer,
	`first_serve_pct` integer,
	`first_serve_win_pct` integer,
	`second_serve_win_pct` integer,
	`aces_per_match` real,
	`double_faults_per_match` real,
	`first_return_win_pct` integer,
	`second_return_win_pct` integer,
	`break_points_converted_pct` integer,
	`return_games_won_pct` integer,
	`clutch_factor` integer,
	`consistency_rating` integer,
	`tiebreak_win_pct` integer,
	`deuce_win_pct` integer,
	`hard_court_win_pct` integer,
	`clay_court_win_pct` integer,
	`grass_court_win_pct` integer,
	`fitness_rating` integer,
	`momentum_rating` real,
	`data_source` text,
	`nationality` text,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `players_slug_unique` ON `players` (`slug`);--> statement-breakpoint
CREATE TABLE `predictions` (
	`id` text PRIMARY KEY NOT NULL,
	`match_id` text NOT NULL,
	`model_version` text NOT NULL,
	`model_type` text NOT NULL,
	`win_prob_a` real NOT NULL,
	`win_prob_b` real NOT NULL,
	`confidence_level` text,
	`deuce_tendency` real,
	`pressure_index` real,
	`predicted_winner_id` text,
	`actual_winner_id` text,
	`was_correct` integer,
	`completed_at` text,
	`notes` text,
	`metadata` text,
	`point_by_point_data` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`match_id`) REFERENCES `matches`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `sources` (
	`id` text PRIMARY KEY NOT NULL,
	`match_id` text NOT NULL,
	`provider` text NOT NULL,
	`url` text,
	`fetched_at` text DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`match_id`) REFERENCES `matches`(`id`) ON UPDATE no action ON DELETE cascade
);
